apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  #resources:
  #  limits:
  #    memory: 2Gi
  #  requests:
  #    memory: 1700Mi
  db:
    vendor: postgres
    host: LNXDBDVLI0016.gp.inet
    port: 5425
    database: Keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
